DROP TABLE Users;
CREATE TABLE Users (
  UserID bigint(20) AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(50) DEFAULT NULL,
  DisplayName varchar(255) DEFAULT NULL,
  Role varchar(255) DEFAULT NULL,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


DROP TABLE DWGs;
CREATE TABLE DWGs (
  dwgID bigint(20) AUTO_INCREMENT PRIMARY KEY,
  URN varchar(255) DEFAULT NULL,
  Version varchar(16) DEFAULT NULL,
  FloorName varchar(255) DEFAULT NULL,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);


DROP TABLE Markup;
CREATE TABLE Markup (
  MarkupID bigint(20) AUTO_INCREMENT PRIMARY KEY,
  UserID bigint(20) NOT NULL,
  dwgID bigint(20) DEFAULT NULL,
  sqrfoot DOUBLE PRECISION DEFAULT NULL,
  ApprovalID bigint(20) default null,
  ApprovalState int DEFAULT NULL,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  json Text DEFAULT NULL
);

DROP TABLE Approvals;
CREATE TABLE Approvals (
  ApprovalID bigint(20) AUTO_INCREMENT PRIMARY KEY,
  ApprovalName varchar(255) DEFAULT NULL,
  State int DEFAULT NULL,
  reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
